package com.resumeai.service;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    private static final DeviceRgb ACCENT = new DeviceRgb(108, 99, 255);
    private static final DeviceRgb DARK   = new DeviceRgb(20, 20, 30);
    private static final DeviceRgb MUTED  = new DeviceRgb(100, 100, 120);

    public byte[] generateResumePdf(String name, String role, String content) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document doc = new Document(pdfDoc);
            doc.setMargins(50, 60, 50, 60);

            var boldFont   = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            var normalFont = PdfFontFactory.createFont(StandardFonts.HELVETICA);

            // Header
            Paragraph header = new Paragraph(name)
                    .setFont(boldFont)
                    .setFontSize(24)
                    .setFontColor(DARK)
                    .setMarginBottom(4);
            doc.add(header);

            Paragraph roleP = new Paragraph(role)
                    .setFont(normalFont)
                    .setFontSize(13)
                    .setFontColor(ACCENT)
                    .setMarginBottom(8);
            doc.add(roleP);

            // Divider line
            LineSeparator ls = new LineSeparator(
                new com.itextpdf.kernel.pdf.canvas.draw.SolidLine(1f));
            ls.setStrokeColor(ACCENT);
            ls.setWidth(UnitValue.createPercentValue(100));
            doc.add(ls);
            doc.add(new Paragraph("").setMarginBottom(10));

            // Content — parse sections by lines starting with capital headers
            String[] lines = content.split("\n");
            for (String line : lines) {
                line = line.trim();
                if (line.isEmpty()) {
                    doc.add(new Paragraph("").setMarginBottom(4));
                } else if (isSectionHeader(line)) {
                    doc.add(new Paragraph(line)
                            .setFont(boldFont)
                            .setFontSize(11)
                            .setFontColor(ACCENT)
                            .setMarginTop(12)
                            .setMarginBottom(4));
                } else if (line.startsWith("•") || line.startsWith("-") || line.startsWith("*")) {
                    String bullet = line.replaceFirst("^[•\\-\\*]\\s*", "");
                    doc.add(new Paragraph("• " + bullet)
                            .setFont(normalFont)
                            .setFontSize(10)
                            .setFontColor(DARK)
                            .setMarginLeft(15)
                            .setMarginBottom(2));
                } else {
                    doc.add(new Paragraph(line)
                            .setFont(normalFont)
                            .setFontSize(10)
                            .setFontColor(DARK)
                            .setMarginBottom(2));
                }
            }

            // Footer
            doc.add(new Paragraph("").setMarginTop(20));
            doc.add(new Paragraph("Generated by resume.ai")
                    .setFont(normalFont)
                    .setFontSize(8)
                    .setFontColor(MUTED)
                    .setTextAlignment(TextAlignment.CENTER));

            doc.close();
        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed: " + e.getMessage(), e);
        }

        return baos.toByteArray();
    }

    public byte[] generateCoverLetterPdf(String name, String company, String content) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document doc = new Document(pdfDoc);
            doc.setMargins(60, 70, 60, 70);

            var boldFont   = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            var normalFont = PdfFontFactory.createFont(StandardFonts.HELVETICA);

            // Header
            doc.add(new Paragraph(name)
                    .setFont(boldFont).setFontSize(20).setFontColor(DARK).setMarginBottom(2));

            if (company != null && !company.isEmpty()) {
                doc.add(new Paragraph("Cover Letter — " + company)
                        .setFont(normalFont).setFontSize(11).setFontColor(ACCENT).setMarginBottom(16));
            }

            LineSeparator ls = new LineSeparator(new com.itextpdf.kernel.pdf.canvas.draw.SolidLine(0.5f));
            ls.setStrokeColor(MUTED);
            doc.add(ls);
            doc.add(new Paragraph("").setMarginBottom(16));

            // Body paragraphs
            for (String para : content.split("\n\n")) {
                para = para.trim();
                if (!para.isEmpty()) {
                    doc.add(new Paragraph(para)
                            .setFont(normalFont)
                            .setFontSize(11)
                            .setFontColor(DARK)
                            .setLineHeight(1.6f)
                            .setMarginBottom(12));
                }
            }

            doc.add(new Paragraph("").setMarginTop(20));
            doc.add(new Paragraph("Generated by resume.ai")
                    .setFont(normalFont).setFontSize(8).setFontColor(MUTED)
                    .setTextAlignment(TextAlignment.CENTER));

            doc.close();
        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed: " + e.getMessage(), e);
        }

        return baos.toByteArray();
    }

    private boolean isSectionHeader(String line) {
        String upper = line.toUpperCase();
        return (upper.equals(line) || line.endsWith(":")) &&
               (upper.contains("SUMMARY") || upper.contains("EXPERIENCE") ||
                upper.contains("EDUCATION") || upper.contains("SKILLS") ||
                upper.contains("ACHIEVEMENTS") || upper.contains("OBJECTIVE") ||
                upper.contains("PROJECTS") || upper.contains("CERTIFICATIONS"));
    }
}
